apiVersion: v1
kind: Secret
metadata:
  name: discord-secret
type: Opaque
data:
  DISCORD_TOKEN: "TVRRek5UYzBOak0yTlRZek5UVTFPVFUxTlEuRzV5QXdULnljM2hTalNKNWZ3WkJURjR2dzRVVTdQMkFOc1VDZ1lJbDl0cU5z" # Substitua pelo token em base64
